/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
>> GP Feature Selection: Exec 0
>> Fim da execucao (14722.142008066177 segundos)

>> GP Feature Selection: Exec 1
>> Fim da execucao (17257.13595032692 segundos)

>> GP Feature Selection: Exec 2
>> Fim da execucao (13558.642605304718 segundos)

>> GP Feature Selection: Exec 3
>> Fim da execucao (7193.9910633563995 segundos)

>> GP Feature Selection: Exec 4
>> Fim da execucao (11753.814384937286 segundos)

>> GP Feature Selection: Exec 5
>> Fim da execucao (39145.22363066673 segundos)

>> GP Feature Selection: Exec 6
>> Fim da execucao (8151.84937787056 segundos)

>> GP Feature Selection: Exec 7
>> Fim da execucao (14374.073475599289 segundos)

>> GP Feature Selection: Exec 8
>> Fim da execucao (13150.571113586426 segundos)

>> GP Feature Selection: Exec 9
>> Fim da execucao (15230.273141860962 segundos)

/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
>> GP Feature Selection: Exec 0
>> Fim da execucao (7555.607127666473 segundos)

>> GP Feature Selection: Exec 1
>> Fim da execucao (9150.314820051193 segundos)

>> GP Feature Selection: Exec 2
>> Fim da execucao (7624.544722795486 segundos)

>> GP Feature Selection: Exec 3
>> Fim da execucao (16613.09881711006 segundos)

>> GP Feature Selection: Exec 4
>> Fim da execucao (23805.60000228882 segundos)

>> GP Feature Selection: Exec 5
>> Fim da execucao (30268.908724308014 segundos)

>> GP Feature Selection: Exec 6
>> Fim da execucao (13402.601728916168 segundos)

>> GP Feature Selection: Exec 7
>> Fim da execucao (9452.948286533356 segundos)

>> GP Feature Selection: Exec 8
>> Fim da execucao (30379.372412204742 segundos)

>> GP Feature Selection: Exec 9
>> Fim da execucao (7400.177425861359 segundos)

/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
>> GP Feature Selection: Exec 0
>> Fim da execucao (17812.334033966064 segundos)

>> GP Feature Selection: Exec 1
>> Fim da execucao (12199.0929749012 segundos)

>> GP Feature Selection: Exec 2
>> Fim da execucao (6427.625114440918 segundos)

>> GP Feature Selection: Exec 3
>> Fim da execucao (11473.854818344116 segundos)

>> GP Feature Selection: Exec 4
>> Fim da execucao (20515.42775940895 segundos)

>> GP Feature Selection: Exec 5
>> Fim da execucao (5839.945962429047 segundos)

>> GP Feature Selection: Exec 6
>> Fim da execucao (17530.897664308548 segundos)

>> GP Feature Selection: Exec 7
>> Fim da execucao (24392.66072678566 segundos)

>> GP Feature Selection: Exec 8
>> Fim da execucao (33337.0594727993 segundos)

>> GP Feature Selection: Exec 9
>> Fim da execucao (14954.708136320114 segundos)

/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
>> GP Feature Selection: Exec 0
>> Fim da execucao (20855.454452753067 segundos)

>> GP Feature Selection: Exec 1
>> Fim da execucao (12659.1057574749 segundos)

>> GP Feature Selection: Exec 2
>> Fim da execucao (11799.363006830215 segundos)

>> GP Feature Selection: Exec 3
>> Fim da execucao (32545.40848827362 segundos)

>> GP Feature Selection: Exec 4
>> Fim da execucao (12710.714738607407 segundos)

>> GP Feature Selection: Exec 5
>> Fim da execucao (8427.16737651825 segundos)

>> GP Feature Selection: Exec 6
>> Fim da execucao (12979.584424972534 segundos)

>> GP Feature Selection: Exec 7
>> Fim da execucao (33045.20594930649 segundos)

>> GP Feature Selection: Exec 8
>> Fim da execucao (18693.429678201675 segundos)

>> GP Feature Selection: Exec 9
>> Fim da execucao (10145.384739637375 segundos)

/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
>> GP Feature Selection: Exec 0
>> Fim da execucao (17536.09511399269 segundos)

>> GP Feature Selection: Exec 1
>> Fim da execucao (23345.938043117523 segundos)

>> GP Feature Selection: Exec 2
>> Fim da execucao (35277.569606781006 segundos)

>> GP Feature Selection: Exec 3
>> Fim da execucao (14240.924680233002 segundos)

>> GP Feature Selection: Exec 4
>> Fim da execucao (21126.268789291382 segundos)

>> GP Feature Selection: Exec 5
>> Fim da execucao (20193.78306031227 segundos)

>> GP Feature Selection: Exec 6
>> Fim da execucao (14660.187665462494 segundos)

>> GP Feature Selection: Exec 7
>> Fim da execucao (46128.82178616524 segundos)

>> GP Feature Selection: Exec 8
>> Fim da execucao (43424.45859646797 segundos)

>> GP Feature Selection: Exec 9
>> Fim da execucao (17007.034949064255 segundos)

/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
>> GP Feature Selection: Exec 0
>> Fim da execucao (29192.463407754898 segundos)

>> GP Feature Selection: Exec 1
>> Fim da execucao (22217.36041021347 segundos)

>> GP Feature Selection: Exec 2
>> Fim da execucao (19489.229095220566 segundos)

>> GP Feature Selection: Exec 3
>> Fim da execucao (32545.286916732788 segundos)

>> GP Feature Selection: Exec 4
>> Fim da execucao (32754.697500944138 segundos)

>> GP Feature Selection: Exec 5
>> Fim da execucao (39703.83560585976 segundos)

>> GP Feature Selection: Exec 6
>> Fim da execucao (22656.295218467712 segundos)

>> GP Feature Selection: Exec 7
>> Fim da execucao (19914.3021171093 segundos)

>> GP Feature Selection: Exec 8
>> Fim da execucao (29915.476652622223 segundos)

>> GP Feature Selection: Exec 9
>> Fim da execucao (25026.85054063797 segundos)

/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
>> GP Feature Selection: Exec 0
>> Fim da execucao (19471.33069562912 segundos)

>> GP Feature Selection: Exec 1
>> Fim da execucao (33484.40147852898 segundos)

>> GP Feature Selection: Exec 2
>> Fim da execucao (24720.57141852379 segundos)

>> GP Feature Selection: Exec 3
>> Fim da execucao (27798.001477479935 segundos)

>> GP Feature Selection: Exec 4
>> Fim da execucao (8192.625239133835 segundos)

>> GP Feature Selection: Exec 5
>> Fim da execucao (35237.83488059044 segundos)

>> GP Feature Selection: Exec 6
>> Fim da execucao (29710.10217308998 segundos)

>> GP Feature Selection: Exec 7
>> Fim da execucao (33947.637263059616 segundos)

>> GP Feature Selection: Exec 8
>> Fim da execucao (42697.75817704201 segundos)

>> GP Feature Selection: Exec 9
>> Fim da execucao (31114.06981229782 segundos)

/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
>> GP Feature Selection: Exec 0
>> Fim da execucao (24936.914895296097 segundos)

>> GP Feature Selection: Exec 1
>> Fim da execucao (31245.975772857666 segundos)

>> GP Feature Selection: Exec 2
>> Fim da execucao (57092.89615941048 segundos)

>> GP Feature Selection: Exec 3
>> Fim da execucao (29669.262915611267 segundos)

>> GP Feature Selection: Exec 4
>> Fim da execucao (26618.671843767166 segundos)

>> GP Feature Selection: Exec 5
>> Fim da execucao (42170.66009259224 segundos)

>> GP Feature Selection: Exec 6
>> Fim da execucao (11122.936002969742 segundos)

>> GP Feature Selection: Exec 7
>> Fim da execucao (17721.461218833923 segundos)

>> GP Feature Selection: Exec 8
>> Fim da execucao (45768.2348780632 segundos)

>> GP Feature Selection: Exec 9
>> Fim da execucao (18596.735881090164 segundos)

Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'operator_set.cpython-35.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-35.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-35.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'operator_set.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'input_output.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'input_output.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'input_output.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'operator_set.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 478, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 476, in rmtree
    os.rmdir(path)
FileNotFoundError: [Errno 2] No such file or directory: '__pycache__'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'operator_set.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    wts_vars.append(int(sys.argv[j]))
ValueError: invalid literal for int() with base 10: 'acc'
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    wts_vars.append(int(sys.argv[j]))
ValueError: invalid literal for int() with base 10: 'acc'
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    wts_vars.append(int(sys.argv[j]))
ValueError: invalid literal for int() with base 10: 'acc'
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    wts_vars.append(int(sys.argv[j]))
ValueError: invalid literal for int() with base 10: 'acc'
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    wts_vars.append(int(sys.argv[j]))
ValueError: invalid literal for int() with base 10: 'acc'
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    wts_vars.append(int(sys.argv[j]))
ValueError: invalid literal for int() with base 10: 'acc'
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    wts_vars.append(int(sys.argv[j]))
ValueError: invalid literal for int() with base 10: 'acc'
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    wts_vars.append(int(sys.argv[j]))
ValueError: invalid literal for int() with base 10: 'acc'
Traceback (most recent call last):
  File "main.py", line 232, in <module>
    wts_vars.append(int(sys.argv[j]))
ValueError: invalid literal for int() with base 10: 'acc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'operator_set.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'input_output.cpython-36.pyc.139828923067568'
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-35.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'operator_set.cpython-35.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-35.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'input_output.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'input_output.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'input_output.cpython-36.pyc.140516492168624'
Traceback (most recent call last):
  File "main.py", line 349, in <module>
    balance = balance)
TypeError: main() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "main.py", line 349, in <module>
    balance = balance)
TypeError: main() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "main.py", line 349, in <module>
    balance = balance)
TypeError: main() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "main.py", line 349, in <module>
    balance = balance)
TypeError: main() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "main.py", line 349, in <module>
    balance = balance)
TypeError: main() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "main.py", line 349, in <module>
    balance = balance)
TypeError: main() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "main.py", line 349, in <module>
    balance = balance)
TypeError: main() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "main.py", line 349, in <module>
    balance = balance)
TypeError: main() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "main.py", line 349, in <module>
    balance = balance)
TypeError: main() got an unexpected keyword argument 'balance'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc.140183226102624'
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    shutil.rmtree("__pycache__")
  File "/root/anaconda3/lib/python3.6/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/root/anaconda3/lib/python3.6/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/root/anaconda3/lib/python3.6/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'fitness_function.cpython-36.pyc.140384302400352'
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:32: RuntimeWarning: invalid value encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
<string>:1: RuntimeWarning: invalid value encountered in double_scalars
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: divide by zero encountered in double_scalars
  return left / right
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'FitnessMulti' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/anaconda3/lib/python3.6/site-packages/deap/creator.py:141: RuntimeWarning: A class named 'Individual' has already been created and it will be overwritten. Consider deleting previous creation of that class or rename it.
  RuntimeWarning)
/root/mpi_projects/icaro/SleepEEG/Exp/operator_set.py:5: RuntimeWarning: invalid value encountered in double_scalars
  return left / right
